repos:
# seed-isort-config disabled for now, see https://github.com/asottile/seed-isort-config/issues/10
#-   repo: https://github.com/asottile/seed-isort-config
#    rev: v1.1.0
#    hooks:
#    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    -   id: flake8
        exclude: elasticapm\/utils\/wrapt|build|src|tests|dist|conftest.py|setup.py
-   repo: /home/beni/elastic/apm-agent-python
    rev: 5cd27336a7950
    hooks:
    - id: license-header-check
